name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # 매일 자정마다 실행
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # 전체 히스토리 가져오기

      - name: Set up Git credentials
        run: |
          git config --global user.name "cbnuLeehyunwoo"
          git config --global user.email "henow123@naver.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: cbnuLeehyunwoo
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Checkout output branch
        run: |
          git checkout -b output || git checkout output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Debug Git Info
        run: |
          git config --list
          git remote -v
          git branch -a
          git status
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
